import "../styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ChakraUiProvider from "components/providers/ChakraUiProvider";
import ReactQueryProvider from "components/providers/ReactQueryProvider";
import VerifyCheckProvider from "components/providers/VerifyCheckProvider";
import ToastProvider from "components/providers/ToastProvider";
import Header from "components/ui/organism/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kwnagyeon-Cho's BLOG",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body className={inter.className}>
        <VerifyCheckProvider>
          <ReactQueryProvider>
            <ChakraUiProvider>
              <ToastProvider>
                <Header />
                {children}
              </ToastProvider>
            </ChakraUiProvider>
          </ReactQueryProvider>
        </VerifyCheckProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
