import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ChakraUiProvider from "components/providers/ChakraUiProvider";
import ReactQueryProvider from "components/providers/ReactQueryProvider";
import VerifyCheckProvider from "components/providers/VerifyCheckProvider";
import ToastProvider from "components/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kwnagyeon-Cho's BLOG",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html>
      <body className={inter.className}>
        <VerifyCheckProvider>
          <ReactQueryProvider>
            <ChakraUiProvider>
              <ToastProvider>{children}</ToastProvider>
            </ChakraUiProvider>
          </ReactQueryProvider>
        </VerifyCheckProvider>
      </body>
    </html>
  );
}
