import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ChakraUiProvider from "providers/ChakraUiProvider";
import ReactQueryProvider from "providers/ReactQueryProvider";
import SessionProvider from "providers/SessionProvider";
import ToastProvider from "providers/ToastProvider";
import Header from "components/ui/organism/Header";
import Footer from "components/ui/organism/Footer";
import { getServerSession } from "next-auth";
import authOptions from "auth.config";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cho's BLOG",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html>
      <body className={inter.className}>
        <SessionProvider>
          <ReactQueryProvider>
            <ChakraUiProvider>
              <ToastProvider>
                <Header session={session} />
                {children}
                <Footer />
              </ToastProvider>
            </ChakraUiProvider>
          </ReactQueryProvider>
        </SessionProvider>
        <SpeedInsights />
        <div id={"modal-root"} />
      </body>
    </html>
  );
}
