import type { Metadata } from "next";
import { ReactNode } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ChakraUiProvider from "@repo/ui/providers/ChakraUiProvider";
import ReactQueryProvider from "@repo/ui/providers/ReactQueryProvider";
import SessionProvider from "@repo/ui/providers/SessionProvider";
import ToastProvider from "@repo/ui/providers/ToastProvider";
import ThemeProvider from "providers/ThemeProvider";
import Header from "components/ui/organism/Header";
import Footer from "components/ui/organism/Footer";
import { getServerSession } from "next-auth";
import authOptions from "auth.config";

import "@repo/tailwind-config/globals.css";

export const metadata: Metadata = {
  title: "Cho's BLOG",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html>
      <body className="font-PretendardRegular">
        <SessionProvider>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <ChakraUiProvider>
                <ToastProvider>
                  <Header session={session} />
                  {children}
                  <Footer />
                </ToastProvider>
              </ChakraUiProvider>
            </ThemeProvider>
          </ReactQueryProvider>
        </SessionProvider>
        <SpeedInsights />
        <div id={"modal-root"} />
      </body>
    </html>
  );
}
