import type { Metadata } from "next";
import { PropsWithChildren } from "react";

import "@repo/tailwind-config/globals.css";

export const metadata: Metadata = {
  title: "Cho's BLOG",
  description: "Generated by create turbo",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
